# Generated by Django 3.1.6 on 2021-02-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_geolocation_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='updated_at',
        ),
    ]
