# Generated by Django 3.1.6 on 2021-02-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_remove_geolocation_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocation',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
